import React from "react";
import { Container, Box, Grid, useTheme } from "@mui/material";
import Head from "next/head";
import Tenant from "../../components/locataire/Tenant";
import RequireAuth from "../../components/Login/RequireAuth";

const TenantP = () => {
  const theme = useTheme();
  return (
    <RequireAuth>
      <Head>
        <title>locative - Mada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="xl" sx={{ bgcolor: theme.palette.common.white }}>
        <Tenant />
      </Container>
    </RequireAuth>
  );
};

export default TenantP;
