import {
  Box,
  Button,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Stack,
  TextField,
  styled,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useAppDispatch } from "../hooks/reduxHooks";
import { changeBorderRadius } from "../redux/slices/customizationSlice";
import SectModules from "../components/home";
import { logout } from "../redux/slices/auth";
import { useRouter } from "next/router";
import LogoutIcon from "@mui/icons-material/Logout";
import RequireAuth from "../components/Login/RequireAuth";

const Home: NextPage = () => {
  const [borderRadius, setBorderRaduis] = useState();
  const dispatch = useAppDispatch();
  const router = useRouter();

  useEffect(() => {}, [borderRadius]);

  const handleBorderRaduis = (e: any) => {
    setBorderRaduis(e.target.value);
    dispatch(changeBorderRadius(e.target.value));
  };

  const couleur = "accent" as any;

  return (
    <RequireAuth>
      <div>
        <Head>
          <title>locative - Mada</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div>
          <Stack
            direction="row"
            sx={{
              flex: "1 1 100%",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <div></div>
            <Button
              sx={{
                display: "flex",
                justifyContent: "space-between",
                flexDirection: "row",
              }}
              onClick={() => {
                dispatch(logout()).unwrap();
                router.push("/login");
              }}
            >
              Deconnexion 
              <LogoutIcon />
            </Button>
          </Stack>
          <DivSectModules>
            <SectModules />
          </DivSectModules>
        </div>
      </div>
    </RequireAuth>
  );
};

export default Home;

const DivSectModules = styled("div")(({ theme }) => ({
  display: "flex",
  flexDirection: "row",
  flexWrap: "wrap",
  justifyContent: "center",
  paddingTop: theme.spacing(16),
  paddingBottom: theme.spacing(4),
  paddingRight: theme.spacing(16),
  paddingLeft: theme.spacing(16),
  margin: "0 auto",
  maxWidth: "100%",
}));
