import React from "react";
import { Container, Box, Grid, useTheme } from "@mui/material";
import Head from "next/head";
import SectionRight from "../../components/Login/sectionRight";
import SectionRegister from "../../components/register";

const Register = () => {
    const theme = useTheme()
  return (
    <>
      <Head>
        <title>Inscription - locative Mada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="xl" sx={{ bgcolor: theme.palette.common.white }}>
        <Box>
          <Grid container spacing={2}>
            <Grid item xs={12} sm={5}>
              <SectionRight />
            </Grid>
            <Grid item xs={12} sm={7}>
              <SectionRegister />
            </Grid>
          </Grid>
        </Box>
      </Container>
    </>
  );
};

export default Register;
