import { Container, Box, Grid, useTheme } from "@mui/material";
import Head from "next/head";
import React from "react";
import SectionRight from "../../components/Login/sectionRight";
import SectionLeft from "../../components/Login/sectionLeft";

const Login = () => {
  const theme = useTheme()
  return (
    <>
      <Head>
        <title>locative - Mada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Container maxWidth="xl" sx={{bgcolor: theme.palette.common.white}}>
        <Box>
          <Grid container spacing={2}>
            <Grid item xs={12} sm={5}>
              <SectionRight/>
            </Grid>
            <Grid item xs={12} sm={7}>
              <SectionLeft/>
            </Grid>
          </Grid>
        </Box>
      </Container>
    </>
  );
};

export default Login;
