import React from "react";
import { Container, useTheme } from "@mui/material";
import Head from "next/head";
import RentCall from "../../components/rent-call/RentCall";

const RentCallP = () => {
    const theme = useTheme()
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="xl" sx={{ bgcolor: theme.palette.common.white }}>
        <RentCall />
      </Container>
    </>
  );
};

export default RentCallP;
